/**********************************************************************************
 
 Copyright (C) 2012 Syed Reza Ali (www.syedrezaali.com)
 
 Permission is hereby granted, free of charge, to any person obtaining a copy of
 this software and associated documentation files (the "Software"), to deal in
 the Software without restriction, including without limitation the rights to
 use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 of the Software, and to permit persons to whom the Software is furnished to do
 so, subject to the following conditions:
 
 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.
 
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
 
 **********************************************************************************/

#pragma once

#define CI_UI_NO_XML 1

//#ifndef CI_UI_NO_XML
//    #include "ofxXmlSettings.h"
//#endif

#ifdef TARGET_OF_IOS
    #define CI_UI_FONT_NAME "GUI/Helvetica.ttf"
#else
    #define CI_UI_FONT_NAME "sans-serif"
#endif

#define CI_UI_FONT_RESOLUTION 150
#define CI_UI_FONT_LARGE_SIZE 10
#define CI_UI_FONT_MEDIUM_SIZE 8
#define CI_UI_FONT_SMALL_SIZE 6

#define CI_UI_LABEL_DRAW_BACK false

#define CI_UI_STATE_NORMAL 0
#define CI_UI_STATE_OVER 1
#define CI_UI_STATE_DOWN 2
#define CI_UI_STATE_SUSTAINED 3

#define CI_UI_GLOBAL_PADDING 2
#define CI_UI_GLOBAL_WIDGET_SPACING 4
#define CI_UI_GLOBAL_CANVAS_WIDTH 211
#define CI_UI_GLOBAL_SLIDER_HEIGHT 16
#define CI_UI_GLOBAL_GRAPH_HEIGHT 64
#define CI_UI_GLOBAL_BUTTON_DIMENSION 16
#define CI_UI_GLOBAL_SPACING_HEIGHT 1

#define CI_UI_COLOR_BACK_ALPHA (100.0f / 255.0f)
#define CI_UI_COLOR_OUTLINE_ALPHA (100.0f / 255.0f)
#define CI_UI_COLOR_OUTLINE_HIGHLIGHT_ALPHA (200.0f / 255.0f)
#define CI_UI_COLOR_FILL_ALPHA (200.0f / 255.0f)
#define CI_UI_COLOR_FILL_HIGHLIGHT_ALPHA 1.0f
#define CI_UI_COLOR_PADDED_ALPHA (100.0f / 255.0f)
#define CI_UI_COLOR_PADDED_OUTLINE_ALPHA (200.0f / 255.0f)

#define CI_UI_COLOR_BACK ciUIColor(0, CI_UI_COLOR_BACK_ALPHA)                                        //rect's back color
#define CI_UI_COLOR_OUTLINE ciUIColor(1.0f, 1.0f, 1.0f, CI_UI_COLOR_OUTLINE_ALPHA)                      //rect's outline color
#define CI_UI_COLOR_OUTLINE_HIGHLIGHT ciUIColor(1.0f, 1.0f, 1.0f, CI_UI_COLOR_OUTLINE_HIGHLIGHT_ALPHA)  //rect's onMouseOver outline highlight color
#define CI_UI_COLOR_FILL ciUIColor(1.0f, 1.0f, 1.0f, CI_UI_COLOR_FILL_ALPHA)                            //rect's fill color
#define CI_UI_COLOR_FILL_HIGHLIGHT ciUIColor(1.0f, 1.0f, 1.0f, CI_UI_COLOR_FILL_HIGHLIGHT_ALPHA)        //rect's onMouseDown highlight color
#define CI_UI_COLOR_PADDED ciUIColor(0, CI_UI_COLOR_PADDED_ALPHA)                                    //rect's padded color
#define CI_UI_COLOR_PADDED_OUTLINE ciUIColor(1.0f, 1.0f, 1.0f, CI_UI_COLOR_PADDED_OUTLINE_ALPHA)        //rect's padded outline color

#define CI_UI_DRAW_PADDING false
#define CI_UI_DRAW_PADDING_OUTLINE false

#define CI_UI_TEXTINPUT_ON_ENTER 0
#define CI_UI_TEXTINPUT_ON_FOCUS 1
#define CI_UI_TEXTINPUT_ON_UNFOCUS 2
#define CI_UI_TEXTINPUT_ON_LOAD 3

#define CI_UI_NUM_OF_THEMES 45

enum ciUIWidgetType
{
	CI_UI_WIDGET_BASE = -1,
	CI_UI_WIDGET_LABEL,
	CI_UI_WIDGET_CANVAS,
	CI_UI_WIDGET_TOGGLE,
	CI_UI_WIDGET_BUTTON,
	CI_UI_WIDGET_SLIDER_H,
	CI_UI_WIDGET_SLIDER_V,
	CI_UI_WIDGET_RSLIDER_H,
	CI_UI_WIDGET_RSLIDER_V,
	CI_UI_WIDGET_NUMBERDIALER,
	CI_UI_WIDGET_RADIO,
	CI_UI_WIDGET_FPS,
	CI_UI_WIDGET_2DPAD,
	CI_UI_WIDGET_TEXTINPUT,
	CI_UI_WIDGET_WAVEFORM,
	CI_UI_WIDGET_SPECTRUM,
	CI_UI_WIDGET_IMAGE,
    CI_UI_WIDGET_LABELBUTTON,
    CI_UI_WIDGET_LABELTOGGLE,
    CI_UI_WIDGET_TOGGLEMATRIX,
    CI_UI_WIDGET_IMAGEBUTTON,
    CI_UI_WIDGET_IMAGETOGGLE,
    CI_UI_WIDGET_ROTARYSLIDER,
    CI_UI_WIDGET_DROPDOWNLIST,
    CI_UI_WIDGET_SPACER,
    CI_UI_WIDGET_MOVINGGRAPH,
    CI_UI_WIDGET_MINIMALSLIDER,
    CI_UI_WIDGET_BILABELSLIDER,
    CI_UI_WIDGET_CIRCLESLIDER,
    CI_UI_WIDGET_IMAGESAMPLER,
	CI_UI_WIDGET_SCROLLABLECANVAS,
    CI_UI_WIDGET_MULTIIMAGEBUTTON,
    CI_UI_WIDGET_MULTIIMAGETOGGLE,
    CI_UI_WIDGET_IMAGESLIDER_H,
    CI_UI_WIDGET_IMAGESLIDER_V,
    CI_UI_WIDGET_CUSTOMIMAGEBUTTON,
    CI_UI_WIDGET_TEXTAREA,
    CI_UI_WIDGET_CUSTOMWIDGET,
    CI_UI_WIDGET_BASE_DRAWS,
    CI_UI_WIDGET_VALUEPLOTTER,
    CI_UI_WIDGET_2DGRAPH,
    CI_UI_WIDGET_SUPERCANVAS,
    CI_UI_WIDGET_TABBAR,
    CI_UI_WIDGET_INTSLIDER_H,
	CI_UI_WIDGET_INTSLIDER_V,
    CI_UI_WIDGET_DOUBLESLIDER_H,
	CI_UI_WIDGET_DOUBLESLIDER_V,
    CI_UI_WIDGET_SORTABLELIST,
    CI_UI_WIDGET_DRAGABLELABELBUTTON,
    CI_UI_WIDGET_ENVELOPEEDITOR
};

enum ciUIWidgetOrientation
{
	CI_UI_ORIENTATION_VERTICAL = 0,
	CI_UI_ORIENTATION_HORIZONTAL = 1
};

enum ciUIWidgetInputDirection
{
	CI_UI_DIRECTION_NORTHSOUTH = 0,
	CI_UI_DIRECTION_SOUTHNORTH = 1,
	CI_UI_DIRECTION_EASTWEST = 2,
	CI_UI_DIRECTION_WESTEAST = 3
};

enum ciUIWidgetAlignment
{
	CI_UI_ALIGN_LEFT = 0,
	CI_UI_ALIGN_FREE = 1,
	CI_UI_ALIGN_RIGHT = 2,
    CI_UI_ALIGN_TOP = 3,
    CI_UI_ALIGN_BOTTOM = 4,
    CI_UI_ALIGN_CENTER = 5
};

enum ciUIWidgetPosition
{
	CI_UI_WIDGET_POSITION_DOWN = 0,
	CI_UI_WIDGET_POSITION_UP = 1,
	CI_UI_WIDGET_POSITION_LEFT = 2,
	CI_UI_WIDGET_POSITION_RIGHT = 3
};

enum ciUIWidgetFontType
{
	CI_UI_FONT_LARGE = 0,
	CI_UI_FONT_MEDIUM = 1,
	CI_UI_FONT_SMALL = 2
};

enum ciUIWidgetColorType
{
	CI_UI_WIDGET_COLOR_BACK = 0,
	CI_UI_WIDGET_COLOR_OUTLINE = 1,
	CI_UI_WIDGET_COLOR_OUTLINE_HIGHLIGHT = 2,
	CI_UI_WIDGET_COLOR_FILL = 3,
	CI_UI_WIDGET_COLOR_FILL_HIGHLIGHT = 4,
    CI_UI_WIDGET_COLOR_PADDED = 5,
	CI_UI_WIDGET_COLOR_PADDED_OUTLINE = 6
    
};

enum ciUITriggerType
{
    CI_UI_TRIGGER_NONE     = 0x00,
    CI_UI_TRIGGER_BEGIN    = 0x01,
    CI_UI_TRIGGER_CHANGE   = 0x02,
    CI_UI_TRIGGER_END      = 0x04,
    CI_UI_TRIGGER_ALL      = 0x07
};

#define ciUITriggerType int

enum ciUIThemeType
{
    CI_UI_THEME_DEFAULT = 0,
    CI_UI_THEME_HACKER,
    CI_UI_THEME_HIPSTER,
    CI_UI_THEME_DIETER,
    CI_UI_THEME_BARBIE,
    CI_UI_THEME_WINDOWS,
    CI_UI_THEME_MACOSX,
    CI_UI_THEME_ZOOLANDER,
    CI_UI_THEME_VEGAN,
    CI_UI_THEME_BERLIN,
    CI_UI_THEME_METALGEAR,
    CI_UI_THEME_TEALLIME,
    CI_UI_THEME_VEGAN2,
    CI_UI_THEME_RUSTIC,
    CI_UI_THEME_MIDNIGHT,
    CI_UI_THEME_MINBLUE,
    CI_UI_THEME_LIMESTONE,
    CI_UI_THEME_SPEARMINT,
    CI_UI_THEME_MINPINK,
    CI_UI_THEME_PEPTOBISMOL,
    CI_UI_THEME_BILEBLUE,
    CI_UI_THEME_COOLCLAY,
    CI_UI_THEME_BLUEBLUE,
    CI_UI_THEME_PINKPANTHER,
    CI_UI_THEME_MAROON,
    CI_UI_THEME_PINKLATTE,
    CI_UI_THEME_MINGREEN,
    CI_UI_THEME_HELLOYELLOW,
    CI_UI_THEME_TEALTEAL,
    CI_UI_THEME_RUSTICORANGE,
    CI_UI_THEME_TEALSALMON,
    CI_UI_THEME_CITRUSBLUE,
    CI_UI_THEME_LIMEPURPLE,
    CI_UI_THEME_LIMESTONE2,
    CI_UI_THEME_COOLPURPLE,
    CI_UI_THEME_GRAYRED,
    CI_UI_THEME_METALGEAR2,
    CI_UI_THEME_LIGHTPINK,
    CI_UI_THEME_MINPINK2,
    CI_UI_THEME_MAXPINK,
    CI_UI_THEME_MINYELLOW,
    CI_UI_THEME_MINLIME,
    CI_UI_THEME_MINORANGE,
    CI_UI_THEME_GRAYDAY,
    CI_UI_THEME_MINBLACK
};
